name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Assuming you have a test script, replace or remove this if not needed

      - name: Build Docker image
        run: docker build -t my-mongo-api .

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Docker image to AWS ECR
        run: |
          docker tag my-mongo-api <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-mongo-api:latest
          docker push <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-mongo-api:latest

      - name: Deploy to AWS EC2
        run: |
          ssh -i /path-to-your-key.pem ec2-user@your-ec2-ip-address <<EOF
          docker pull <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-mongo-api:latest
          docker stop my-mongo-api || true
          docker rm my-mongo-api || true
          docker run -d -p 80:3000 --name my-mongo-api <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-mongo-api:latest
          EOF
